### ISSUE TITLE
Editor doesn't work on new game save

### ISSUE THREAD

**Issue by WilsonZiweiWang** [G40styBoy/Infinity-Blade-3-Save-Editor#1]
First, thank you so much for this editor! 

I just came across your post about the editor on Redit and it led me to this repo. I followed your video and sideloaded the game and downloaded your editor, then I exported the save file after I finished the tutorial (before the 1st awakening). I ran the editor and tried to edit the currency, the numbers were all `-1`. It appears something went wrong with the `FindAndReadValue()`. After I finished the 1st awakening, the editor showed the correct number the edit was no problem so it was all good in the end. Because I never coded with C# before I decided to post an issue here.

Anyways, good job on your work! Now I can enjoy this game once again!

**Comment by G40styBoy** [comment]
Hi there, thanks for opening an issue and apologies for not getting back quicker! The reason this occurred is because until currency is gained, the currency struct isn't populated inside of the save. 

I don't think this will be updated again since its very old code, and im working on a new save editor project that's in a functioning state. Nevertheless thank you for letting me know about this issue, im glad you got it working!

**Comment by WilsonZiweiWang** [comment]
Thanks for responding! Looking forward to your new editor!
